services:
  backend:
    build: ./backend
    ports:
      - "7001:7001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
